### PR TITLE
addRecipient function

### PR DESCRIPTION
**Pull request by bnayal**
This commit adds the addRecipient function of the XML api

### CODE REVIEW

**Comment by rtirserio** [comment]
any chance this gets merged in?

**Comment by lafiosca** [comment]
@bnayal Previously we did not have permission to accept code contributions, but we have updated the README.md file with information on how to contribute code going forward. We need you to read the new "Contributing" section of the README.md file as well as the Developer's Certificate of Origin (DCO) file that it links to. Please follow those new directions to update your pull request with a commit message including your DCO signoff, and we will be able to accept the contribution. I apologize for the small inconvenience.

**Comment by rtirserio** [comment]
@bnayal can you update your commit so this gets merged?

**Comment by lafiosca** [comment]
@rtirserio I am intending to spend some time adding several of the missing API methods myself during the week of May 16th-20th. If @bnayal has not signed off on the DCO by then, I will include addRecipient in my targeted list of methods.

**Comment by rtirserio** [comment]
Great, thanks @lafiosca. I just started working on `DoubleOptInRecipient`.

**Comment by bnayal** [comment]
Not sure why I need to include my email address in a commit, but here it is...

**Comment by lafiosca** [comment]
@bnayal Thank you
Heads up, @rtirserio

**Pull request merged**
